#!/usr/bin/bash
#colores

	export negro='\033[1;30m'
        export red='\033[1;31m'
        export green='\033[1;32m'
        export yellow='\033[1;33m'
        export blue='\033[1;34m'
        export magenta='\033[1;35m'
        export cyan='\033[1;36m'
	export white='\033[0m'
	#banner

function banner {
        echo $(clear)
	printf "$red
              :*=@@WW@@=*:
         -=WWWWW@#=***#@WWWWW=- $white         _   _       _$red
      .=WWW#:..............:#WWW=       $white| \ | | ___ | |_$red
     #WW#-....................-#WW#     $white|  \| |/ _ \| __|$red
   +WW#........$white-=WWWWWW=-$red........#WW+   $white| |\  | (_) | |_ $red
  =WW+.......$white-@WW=:$red--$white:=WW@-$red.......+WW=  $white|_| \_|\___/ \__|$red
 *WW:.......$white-WW#$red........$white=WW-$red.......:WW* $white _____                     _$red
:WW+........$white*W@-$red........$white-WW*$red........+WW $white|  ___|__  _   _ _ __   __| |$red
=W@.....................$white:WW+$red.........@W $white| |_ /   \| | | | '_ \ /    |$red
@W=....................$white*WW=$red..........*W $white|  _| (_) | |_| | | | | (_) |$red
WW*...............$white-#WWWW@:$red...........*W $white|_|  \___/ \__,_|_| |_|\__,_|$red
@W#...............$white:WW*-$red..............=W
*WW-.....---:.---.$white:WW:$red::-........--.-WW
 @W#.....---:---:.$white:WW:$red:.-:-:::-:::-.#W@
  WW#..............................#WW
   @W@-...........$white:WW:$red...........-@W@
    =WW#..........$white-**-$red..........#WW=
       #WW@+..................+@WW#        
        +@WWW#+-........-+#WWW@+           
            *@WWWWWWWWWWWW@*
$white"

}
banner
setterm --background red
echo
sleep 2
printf "$yellow :: Disclaimer  Developers assume no liability and are not    ::\n"
sleep 2
setterm --background black
setterm --background red
printf "$yellow :: responsible for any misuse or damage caused by NOT?FOUND  ::\n"
sleep 3 
setterm --background black
echo
printf "$green             the team not found is \n"
sleep 3
printf "$green             formed by a variety of \n"
sleep 3
printf "$green             people, who aspire to \n"
sleep 3
printf "$green             programming, or ethical \n"
sleep 3
printf "$green             hacking, will be creating  \n"
sleep 3
printf "$green             tools or script every time or \n"
sleep 3
printf "$green             you can contact us for \n"
sleep 3
printf "$green             suggestions.\n"
echo
printf "$green"
echo
printf "$green        
           1) Traducir

           2) MENU PY
	   
	   3) MENU BASH

	   0) Exit//Salir
"
echo
read -p "Chose an Option >> " z
case $z in                                                             
	1)
		banner                                                 
		echo
		printf "$green
   ::::::: TRANSLATE ::::::::"             
		echo
		sleep 5                                                
		bash spanish                               
		;;
	2)
		banner
		printf "$green           ::::: MENU PY :::::::"
		sleep 5
		echo
		python menu.py
		;;
	3)
		banner
		printf "$green            :::: MENU BASH ::::"
		sleep 5
		bash menu
		;;
	0)
		exit
esac


