#!/bin/bash
        export negro='\033[1;30m'
        export red='\033[1;31m'
        export green='\033[1;32m'
        export yellow='\033[1;33m'
        export blue='\033[1;34m'
        export magenta='\033[1;35m'
        export cyan='\033[1;36m'
        export white='\033[0m'
clear
printf "$red
              :*=@@WW@@=*:
         -=WWWWW@#=***#@WWWWW=- $white         _   _       _$red
      .=WWW#:..............:#WWW=       $white| \ | | ___ | |_$red
     #WW#-....................-#WW#     $white|  \| |/ _ \| __|$red
   +WW#........$white-=WWWWWW=-$red........#WW+   $white| |\  | (_) | |_ $red
  =WW+.......$white-@WW=:$red--$white:=WW@-$red.......+WW=  $white|_| \_|\___/ \__|$red
 *WW:.......$white-WW#$red........$white=WW-$red.......:WW* $white _____                     _$red
:WW+........$white*W@-$red........$white-WW*$red........+WW $white|  ___|__  _   _ _ __   __| |$red
=W@.....................$white:WW+$red.........@W $white| |_ /   \| | | | '_ \ /    |$red
@W=....................$white*WW=$red..........*W $white|  _| (_) | |_| | | | | (_) |$red
WW*...............$white-#WWWW@:$red...........*W $white|_|  \___/ \__,_|_| |_|\__,_|$red
@W#...............$white:WW*-$red..............=W
*WW-.....---:.---.$white:WW:$red::-........--.-WW
 @W#.....---:---:.$white:WW:$red:.-:-:::-:::-.#W@
  WW#..............................#WW
   @W@-...........$white:WW:$red...........-@W@
    =WW#..........$white-**-$red..........#WW=
      #WW@+..................+@WW#         
        +@WWW#+-........-+#WWW@+           
            *@WWWWWWWWWWWW@*
$white"
sleep 7
for i in ---------@ TEAM------------@ NOT---------@ FOUND----------@ TEAM-NOT-FOUND; do
	printf "$G $(clear) STARTING TO INSTALL . . . .$W$i\n\n"
	sleep 4
done
echo
echo
printf "$cyan ==================================$white 
$magenta Instalando los paquetes necesarios$white 
$cyan ==================================$white
"
apt install -y util-linux
apt install -y python
apt install -y php
apt install -y openssh
pip install colorama
sleep 1
printf "$cyan ========================$white
$magenta Todo listo para ejecutar$white
$cyan ========================$white
$red    @Not-Found-Team   $white
"
sleep 2
printf "$yellow Elegir Lenguaje // set Languague$white
$green 1) English$white
$green 2) Español$white
"
echo
read -p ">> " opc
case $opc in
1)
	bash english
	;;
2)
	bash spanish
	;;
esac
