#!/usr/bin/bash
#colores

	export negro='\033[1;30m'
        export red='\033[1;31m'
        export green='\033[1;32m'
        export yellow='\033[1;33m'
        export blue='\033[1;34m'
        export magenta='\033[1;35m'
        export cyan='\033[1;36m'
	export white='\033[0m'
	#banner

function banner {
        echo $(clear)
	printf "$red
              :*=@@WW@@=*:
         -=WWWWW@#=***#@WWWWW=- $white         _   _       _$red
      .=WWW#:..............:#WWW=       $white| \ | | ___ | |_$red
     #WW#-....................-#WW#     $white|  \| |/ _ \| __|$red
   +WW#........$white-=WWWWWW=-$red........#WW+   $white| |\  | (_) | |_ $red
  =WW+.......$white-@WW=:$red--$white:=WW@-$red.......+WW=  $white|_| \_|\___/ \__|$red
 *WW:.......$white-WW#$red........$white=WW-$red.......:WW* $white _____                     _$red
:WW+........$white*W@-$red........$white-WW*$red........+WW $white|  ___|__  _   _ _ __   __| |$red
=W@.....................$white:WW+$red.........@W $white| |_ /   \| | | | '_ \ /    |$red
@W=....................$white*WW=$red..........*W $white|  _| (_) | |_| | | | | (_) |$red
WW*...............$white-#WWWW@:$red...........*W $white|_|  \___/ \__,_|_| |_|\__,_|$red
@W#...............$white:WW*-$red..............=W
*WW-.....---:.---.$white:WW:$red::-........--.-WW
 @W#.....---:---:.$white:WW:$red:.-:-:::-:::-.#W@
  WW#..............................#WW
   @W@-...........$white:WW:$red...........-@W@
    =WW#..........$white-**-$red..........#WW=
      #WW@+..................+@WW#         $green 1) ENGLISH$red
        +@WWW#+-........-+#WWW@+           $green 0) SALIR$red
            *@WWWWWWWWWWWW@*
$white"

}
banner
setterm --background red
echo
sleep 2
printf "$yellow :: responsabilidad no se asumen ninguna responsabilidad y no son  ::\n"
sleep 2
setterm --background black
setterm --background red
printf "$yellow :: responsable de cualquier mal uso o daño causado por NOT? FOUND ::\n"
sleep 3 
setterm --background black
echo
printf "$green             el equipo not found es \n"
sleep 3
printf "$green             formado por una variedad de \n"
sleep 3
printf "$green             personas que aspiran a \n"
sleep 3
printf "$green             programación o ética\n"
sleep 3
printf "$green             hacking, estaremos creando  \n"
sleep 3
printf "$green             herramientas o script cada vez o \n"
sleep 3
printf "$green             puede contactar con nosotros para \n"
sleep 3
printf "$green             sugerencias.\n"
echo
sleep 5
printf "$green"
echo
printf "$green      
        2) MENU PY

        3) MENU BASH
"
echo
read -p "Elije Una Opcion >> " z
case $z in
        1)
                banner
                echo
                printf "$green                                             ::::::: TRANSLATE ::::::::"
                echo                                                                    sleep 5
                bash english
                ;;
        2)
                banner
                printf "$green        ::::: MENU PY :::::::"
                sleep 5
                echo
		python menu.py
                ;;
        3)
                banner
                printf "$green         :::: MENU BASH ::::"
                sleep 5
                bash menu
                ;;
        0)
                exit
esac
